name: staging

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest #24

    steps:
    - name: Checkout SCM
      uses: actions/checkout@v4 

    - name: Build Docker Image
      run: docker build -t alvindra/dumbflix-fe:latest .

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Images
      run: docker push alvindra/dumbflix-fe:latest

  deploy:

    runs-on: ubuntu-latest #24     

    steps:
    - name: SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        port: 22
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key:  ${{ secrets.SSH_KEY }}
        script: |
           docker compose -f ${{ secrets.COMPOSE_FILE }} pull
           docker compose -f ${{ secrets.COMPOSE_FILE }} down
           docker compose -f ${{ secrets.COMPOSE_FILE }} up -d
